apiVersion: v1
kind: Namespace
metadata:
  name: transmission
  labels:
    name: transmission

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-movies
  namespace: transmission
  labels:
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/radarr/movies"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config
  namespace: transmission
  labels:
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/radarr/config"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-movies
  namespace: transmission
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: transmission
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: transmission
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      volumes:
        - name: transmission-downloads
          persistentVolumeClaim:
            claimName: transmission-downloads
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: radarr-movies
          persistentVolumeClaim:
            claimName: radarr-movies
      containers:
      - name: radarr
        image: linuxserver/radarr:amd64-latest
        ports:
        - containerPort: 8989
        volumeMounts:
          - mountPath: /config
            name: radarr-config
          - mountPath: /downloads
            name: transmission-downloads
          - mountPath: /movies
            name: radarr-movies

---

apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: transmission
spec:
  selector:
    app: radarr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7878

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: radarr
  namespace: transmission
spec:
  rules:
  - http:
      paths:
      - path: /radarr
        backend:
          serviceName: radarr
          servicePort: 80
